const app = document.querySelector('#app');
const state = { page:'landing', quiz:0, answers:[], rsvp:false, event:'book', tab:'upcoming', added:false };
const events = [
  {id:'run',title:'Sunday Sunrise Run',area:'Hauz Khas Village',date:'Sun, 7:00 AM',people:'24 going',match:'96% match',cls:'run',why:'You both value movement, calm mornings and low-pressure conversations.'},
  {id:'book',title:'The Quiet Book Club',area:'GK II',date:'Sat, 5:30 PM',people:'18 going',match:'93% match',cls:'book',why:'Your love of stories and thoughtful, smaller circles makes this a strong fit.'},
  {id:'art',title:'Paint & Chai Evening',area:'Lajpat Nagar',date:'Fri, 6:30 PM',people:'31 going',match:'89% match',cls:'art',why:'You value creativity and said your best conversations happen while doing something together.'},
  {id:'hike',title:'Aravalli Day Hike',area:'Gurugram',date:'Sun, 6:00 AM',people:'16 going',match:'86% match',cls:'hike',why:'Curious people, fresh air and a shared preference for making plans over endless texting.'}
];
function nav(){return `<div class="topbar"><button class="brand" onclick="go('landing')">togather<small>Delhi-NCR</small></button><div class="nav"><span onclick="go('feed')">Discover</span><span onclick="go('myevents')">My events</span><span onclick="go('organizer')">For organizers</span><button class="avatar" onclick="go('profile')">AV</button></div></div>`}
function bottom(active){return `<div class="bottomnav"><button class="${active==='feed'?'active':''}" onclick="go('feed')">Discover</button><button class="${active==='myevents'?'active':''}" onclick="go('myevents')">My events</button><button class="${active==='organizer'?'active':''}" onclick="go('organizer')">Host</button><button class="${active==='profile'?'active':''}" onclick="go('profile')">Profile</button></div>`}
function landing(){return `<section class="screen"><div class="shell">${nav()}<div class="hero"><div><div class="eyebrow">REAL PEOPLE. REAL PLANS.</div><h1>Meet people<br>who get you.</h1><p>Neighbourhood events in Delhi-NCR, matched to your values, interests and social style — not just your calendar.</p><button class="primary" onclick="go('quiz')">Find your people</button></div><div class="hero-art"><div class="sun"></div><div class="hill one"></div><div class="hill two"></div><div class="people"><div class="person"></div><div class="person"></div><div class="person"></div></div><div class="float one">✦ 93% your kind of people</div><div class="float two">Delhi-NCR is happening</div></div></div><div class="features"><div class="feature"><span class="icon">✦</span><b>Compatibility first</b><p>A short quiz points you to rooms where you are likely to click.</p></div><div class="feature"><span class="icon">⌖</span><b>Truly hyperlocal</b><p>Small, real things happening in your part of the city.</p></div><div class="feature"><span class="icon">◎</span><b>Good hosts</b><p>Simple tools for people who make community happen.</p></div><div class="feature"><span class="icon">↗</span><b>Keep the spark</b><p>Reconnect with people you actually met after the event.</p></div></div></div></section>`}
const questions=[['What matters most to you?','Pick up to two values that shape your decisions.',['Curiosity','Creativity','Wellbeing','Community']],['Your social battery is usually...','There is no wrong answer here.',['Quiet at first, warm later','Energised by a crowd','Best in small groups','Always up for something new']],['What would you happily make time for?','Choose the things that pull you out of the house.',['Books & ideas','Running & outdoors','Art & music','Food & culture']],['Where do you feel most at home?','We will keep your feed close by.',['Hauz Khas / Saket','GK / Lajpat Nagar','Connaught Place','Dwarka / Janakpuri']],['One thing you would rather skip?','This helps us avoid mismatches.',['Huge crowds','Networking pressure','Late nights','Drinking-focused plans']]];
function quiz(){let q=questions[state.quiz], pct=(state.quiz/5)*100; return `<section class="screen"><div class="shell"><button class="brand" onclick="go('landing')">togather</button><div class="onboard"><div class="eyebrow">YOUR COMPATIBILITY PROFILE</div><h1>Let’s make the next plan feel right.</h1><div class="progress"><i style="width:${pct+10}%"></i></div><div class="question"><div class="tag">QUESTION ${state.quiz+1} OF 5</div><h2>${q[0]}</h2><p>${q[1]}</p><div class="options">${q[2].map(x=>`<button class="option ${state.answers[state.quiz]===x?'selected':''}" onclick="answer('${x}')">${x}</button>`).join('')}</div></div><div class="quiznav"><button class="secondary" onclick="backQuiz()" ${state.quiz===0?'disabled':''}>Back</button><button class="primary" onclick="nextQuiz()">${state.quiz===4?'See my matches':'Continue'}</button></div></div></div></section>`}
function eventCard(e){return `<article class="event" onclick="openEvent('${e.id}')"><div class="eventimg ${e.cls}"><span>✦ ${e.match}</span></div><div class="eventbody"><h3>${e.title}</h3><div class="meta">${e.area}<br>${e.date} · ${e.people}</div><div class="eventfoot"><span class="match">${e.match}</span><button class="rsvp">View event</button></div></div></article>`}
function feed(){return `<section class="screen"><div class="shell">${nav()}<div class="feed"><aside class="sidebar"><h3>Explore near you</h3><button class="filter active">For you</button><button class="filter">Hauz Khas</button><button class="filter">GK & Lajpat</button><button class="filter">CP</button><button class="filter">Outdoors</button><button class="filter">Creative</button></aside><div><div class="pagehead"><div><div class="eyebrow">YOUR WEEKEND, BETTER MATCHED</div><h1>Plans that feel like you.</h1><p>Based on creativity, small groups and your neighbourhood.</p></div><button class="secondary" onclick="go('profile')">Tune matches</button></div><div class="events">${events.map(eventCard).join('')}${state.added?eventCard({id:'new',title:'Coffee & Ideas Circle',area:'Hauz Khas Village',date:'Thu, 6:30 PM',people:'New listing',match:'91% match',cls:'run'}):''}</div></div></div>${bottom('feed')}</div></section>`}
function detail(){let e=events.find(x=>x.id===state.event)||events[1];return `<section class="screen"><div class="shell">${nav()}<div class="detail"><button class="secondary" onclick="go('feed')">← All events</button><div class="cover ${e.cls}"><span class="match">✦ ${e.match}</span></div><article><div class="eyebrow">${e.area}</div><h1>${e.title}</h1><div class="meta">${e.date} · ${e.people} · Hosted by Neighbourhood People</div><div class="why"><b>Why this matches you</b><br>${e.why}</div><p>This is a gentle, easy-going meet-up for people looking to share an interest and leave with a few familiar faces. Come as you are.</p><button class="primary" onclick="rsvp()">${state.rsvp?'You’re going ✓':'RSVP to this event'}</button></article></div>${bottom('feed')}</div></section>`}
function myevents(){return `<section class="screen"><div class="shell">${nav()}<div class="detail"><div class="pagehead"><div><div class="eyebrow">YOUR PLANS</div><h1>My events</h1></div></div><div class="tabs"><button class="${state.tab==='upcoming'?'active':''}" onclick="setTab('upcoming')">Upcoming</button><button class="${state.tab==='past'?'active':''}" onclick="setTab('past')">Past & connections</button></div>${state.tab==='upcoming'?`<div class="events">${state.rsvp?eventCard(events.find(e=>e.id===state.event)):''}${!state.rsvp?'<p class="meta">Nothing RSVPed yet. Your next good plan is waiting in Discover.</p>':''}</div>`:`<div><div class="event"><div class="eventbody"><h3>Hauz Khas Sunday Run</h3><div class="meta">Last Sunday · You met 4 people</div></div></div><h2 style="margin-top:28px">People you met</h2><div class="connections">${['Meera · 94% match','Kabir · 90% match','Naina · 87% match'].map((x,i)=>`<div class="connection"><div class="face">${['M','K','N'][i]}</div><div class="copy"><b>${x}</b><small>${['Also loves early starts and poetry','Into trails and unhurried conversations','Keeps a running playlist'][i]}</small></div><button class="secondary" onclick="this.textContent='Connected ✓'">Connect</button></div>`).join('')}</div></div>`}</div>${bottom('myevents')}</div></section>`}
function organizer(){return `<section class="screen"><div class="shell">${nav()}<div class="organizer"><div class="eyebrow">FOR COMMUNITY ORGANIZERS</div><h1>Bring your next gathering to the right people.</h1><p class="meta">List an event in a few minutes. We will put it in front of people likely to come back.</p><div class="question">${state.added?'<div class="success"><div class="icon">✦</div><h2>Your event is live.</h2><p>It is now showing to compatible people nearby.</p><button class="primary" onclick="go(\'feed\')">See it in Discover</button></div>':`<div class="formgrid"><input placeholder="Event name" value="Coffee & Ideas Circle"><select><option>Hauz Khas Village</option><option>GK II</option><option>Connaught Place</option></select><input placeholder="Date & time" value="Thursday, 6:30 PM"><textarea rows="4" placeholder="What will people do?">An easy, hosted space for ideas, neighbourhood stories and good coffee.</textarea><button class="primary" onclick="publish()">Publish event</button></div>`}</div></div>${bottom('organizer')}</div></section>`}
function profile(){return `<section class="screen"><div class="shell">${nav()}<div class="profilecard"><div class="face" style="height:62px;width:62px;font-size:20px">AV</div><h1 style="font-family:Fraunces;margin-bottom:5px">Ayush Vaidya</h1><p class="meta">Hauz Khas Village · Delhi-NCR</p><span class="verified">✓ Verified member</span><hr style="border:0;border-top:1px solid #e6ddcd;margin:24px 0"><h3>Your compatibility profile</h3><p class="meta">Creative, small-group person · Books & ideas · No networking pressure</p><button class="secondary" onclick="go('quiz')">Edit profile</button></div>${bottom('profile')}</div></section>`}
function render(){app.innerHTML=({landing,quiz,feed,detail,myevents,organizer,profile}[state.page])()}function go(p){state.page=p;render();scrollTo(0,0)}function answer(v){state.answers[state.quiz]=v;render()}function nextQuiz(){if(!state.answers[state.quiz])return;if(state.quiz<4){state.quiz++;render()}else go('feed')}function backQuiz(){if(state.quiz){state.quiz--;render()}}function openEvent(id){state.event=id;go('detail')}function rsvp(){state.rsvp=true;render()}function setTab(t){state.tab=t;render()}function publish(){state.added=true;render()}render();
